# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8628fc51ce4ef01772d86633514d9527d3e0182322778d2b611917c3419e2da0186ad956e5214b4a75d6dc904991919b18f9c20cab81f79a809fad8c1af76e71

test:
  secret_key_base: 4e441b153d991998974e0d31e303f960b7ed59778878708dbf1b35a060e3ef3d12c8df833be5d2c29bc2a15ad8756ee6aa0395d7fba4c8ec7e777f0d08ae61d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
